from dsa.ds1 import*
def main():
    # introduce_python_collections()
    # introduce_numpy_array()
    # numpy_anatomy()
    # create_numpy_array_from_python_collection()
    # create_numpy_array_from_functions()
    # create_numpy_array_from_special_functions()
    # vectorizations_vs_python_loops()
    # arithmatic_operations()
    # trigonomic_functions()
    # rounding_functions()
    # exponent_logarithm()
    # miscellaneous_functions()
    # indexing_and_slicing_one_dimension_array()
    # indexing_and_slicing_multi_dimension_array()
    #  mask_indexing()
    # numpy_indexing_functions()
    # array_iteration()
    # shallow_copy_numpy_array()
    # deep_copy_numpy_array()
    # array_manipulation()
    # random_numbers()
    # binomial_distribution()
    # chi_square_distribution()
    poisson_distribution()

if __name__ == "__main__":
    main()